# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            'Minimal Computing workshop'
tagline:          'MinComp Workshop @ SFU'
description:      'Minimal Computing workshop at SFU. Themed based on <a href="https://github.com/poole/hyde">Hyde</a>'
baseurl:          http://joeytakeda.github.io/mincomp/

author:
  name:           'Joey Takeda'
  url:            https://github.com/joeytakeda

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/joeytakeda/mincomp
